[module.hugoVersion]
min = "0.141.0"

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hb.revision]
date_format = ":date_full"
icons = true
font_size = ".825rem"
created_at = true
repo_service = ""
repo_subpath = ""
